import { Poppins as PoppinsFont } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const Poppins = PoppinsFont({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Poppins.variable}>
        <div className=" mx-auto w-[1440px]">
        {children}
        <Footer/>
        </div>
       
        </body>
    </html>
  );
}
